export default {
	"0": "Invalid District",
	"99999": "Invalid District",
	"ALAP": "Alapaha Judicial Circuit",
	"ALCO": "Alcovy Judicial Circuit",
	"APPA": "Appalachian Judicial Circuit",
	"ATLA": "Atlanta Judicial Circuit",
	"ATLC": "Atlantic Judicial Circuit",
	"AUGU": "Augusta Judicial Circuit",
	"BELL": "Bell-Forsyth Judicial Circuit",
	"BLRD": "Blue Ridge Judicial Circuit",
	"BRUN": "Brunswick Judicial Circuit",
	"CHAT": "Chattahoochee Judicial Circuit",
	"CHER": "Cherokee Judicial Circuit",
	"CLAY": "Clayton Judicial Circuit",
	"COBB": "Cobb Judicial Circuit",
	"CONA": "Conasauga Judicial Circuit",
	"CORD": "Cordele Judicial Circuit",
	"COWE": "Coweta Judicial Circuit",
	"DHRT": "Dougherty Judicial Circuit",
	"DOUG": "Douglas Judicial Circuit",
	"DUBL": "Dublin Judicial Circuit",
	"EAST": "Eastern Judicial Circuit",
	"ENOT": "Enotah Judicial Circuit",
	"FLIN": "Flint Judicial Circuit",
	"GRIF": "Griffin Judicial Circuit",
	"GWIN": "Gwinnett Judicial Circuit",
	"HOUS": "Houston Judicial Circuit",
	"LOMO": "Lookout Mountain Judicial Circuit",
	"MACO": "Macon Judicial Circuit",
	"MIDD": "Middle Judicial Circuit",
	"MONT": "Mountain Judicial Circuit",
	"NEST": "Northeastern Judicial Circuit",
	"NRTH": "Northern Judicial Circuit",
	"OCMU": "Ocmulgee Judicial Circuit",
	"OCON": "Oconee Judicial Circuit",
	"OGEE": "Ogeechee Judicial Circuit",
	"PATA": "Pataula Judicial Circuit",
	"PAUL": "Paulding Judicial Circuit",
	"PIED": "Piedmont Judicial Circuit",
	"ROCK": "Rockdale Judicial Circuit",
	"ROME": "Rome Judicial Circuit",
	"SOGA": "South Georgia Judicial Circuit",
	"STHN": "Southern Judicial Circuit",
	"STMT": "Stone Mountain Judicial Circuit",
	"SWST": "Southwestern Judicial Circuit",
	"TALL": "Tallapoosa Judicial Circuit",
	"TIFT": "Tifton Judicial Circuit",
	"TOOM": "Toombs Judicial Circuit",
	"TOWA": "Towaliga Judicial Circuit",
	"WAYC": "Waycross Judicial Circuit",
	"WEST": "Western Judicial Circuit"
};
